### ISSUE TITLE
关于CodeField中的TypeValue与TypeKey的含义

### ISSUE THREAD

**Issue by wuwen5** [modernizing/chapi#20]
```kotlin
open class CodeField(
    var TypeType: String = "",
    var TypeValue: String = "",
    var TypeKey: String = "",
    var Annotations: Array<CodeAnnotation> = arrayOf(),
    var Modifiers: Array<String> = arrayOf(),
    // for TypeScript and JavaScript only, examples: `export default sample = createHello() `
    var Calls: Array<CodeCall> = arrayOf()
)
```

例如code如下

```java
class Demo {
    private String name = "abc";
}
```

解析后，`TypeType=String`、`TypeValue=name`、`TypeKey=""`
`TypeKey`到底是指的什么呢？

我理解是否应该 `TypeKey=name`、 `TypeValue="abc"` ?

看下了，`chapi-ast-kotlin` 和`chapi-ast-typescript`中 是正确的
是否为 `chapi-ast-java` 的bug？

**Comment by phodal** [comment]
啊，应该是个 bug 了。第一个版本写的时候是 Java，所以只有 Key 和 Type，没有记录值（"abc"）。好像是，后来引入 TypeScript 和 Kotlin 的时候，新加了一个 Value，可以根据 Value 做一些简单的类型推断。

要来个 PR 吗？

**Comment by wuwen5** [comment]
ok, 确认为bug，我尝试下解决.
